version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: swifthire-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swifthire-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/swift_hire_db
    depends_on:
      - mongo

volumes:
  mongo_data:
