services:
  mongo:
    image: mongo:latest
    container_name: swifthire-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swifthire-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.compose
    volumes:
      - ./swifthire-458117-50f3c5f19084.json:/app/swifthire-458117-50f3c5f19084.json  # Mount the credentials file
    depends_on:
      - mongo

volumes:
  mongo_data:
